### ISSUE TITLE
Returning image data back to flutter instead of writing to file

### ISSUE THREAD

**Issue by deathg0d** [abhishekove/simple-edge-detection#1]
Hi. Great work. Just a small question. I see that you have used process_image to implement wrapPerspective to crop and transform image. At the end after transforming it writes (modifies) the same file (and returns a bool to flutter). Is there a way to return **image data** back to Flutter without writing to the existing file?

**Comment by abhishekove** [comment]
I am not sure but I think it is possible as you can return the image and call the function and handle that data in the flutter.
